// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvpimOVtGpH7AZ-GmQoMILeJpR2ddsAxQ',
    appId: '1:491513753482:web:339a0606308ec30cd0e273',
    messagingSenderId: '491513753482',
    projectId: 'hangnobita-52b73',
    authDomain: 'hangnobita-52b73.firebaseapp.com',
    databaseURL: 'https://hangnobita-52b73-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hangnobita-52b73.firebasestorage.app',
    measurementId: 'G-VTENEMJ2JG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLrUb2pJlutJebZFaXwK5aMjxlT0jrnvQ',
    appId: '1:491513753482:android:298928496ca95db8d0e273',
    messagingSenderId: '491513753482',
    projectId: 'hangnobita-52b73',
    databaseURL: 'https://hangnobita-52b73-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hangnobita-52b73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUPvXxAorM-TVnpS-szaz1lR5DNFptr-w',
    appId: '1:491513753482:ios:5688af3e01a485c4d0e273',
    messagingSenderId: '491513753482',
    projectId: 'hangnobita-52b73',
    databaseURL: 'https://hangnobita-52b73-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hangnobita-52b73.firebasestorage.app',
    iosClientId: '491513753482-nk2dfppt3o4m2ujfijq3v1pbtts3232b.apps.googleusercontent.com',
    iosBundleId: 'com.example.betterhalf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUPvXxAorM-TVnpS-szaz1lR5DNFptr-w',
    appId: '1:491513753482:ios:5688af3e01a485c4d0e273',
    messagingSenderId: '491513753482',
    projectId: 'hangnobita-52b73',
    databaseURL: 'https://hangnobita-52b73-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hangnobita-52b73.firebasestorage.app',
    iosClientId: '491513753482-nk2dfppt3o4m2ujfijq3v1pbtts3232b.apps.googleusercontent.com',
    iosBundleId: 'com.example.betterhalf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvpimOVtGpH7AZ-GmQoMILeJpR2ddsAxQ',
    appId: '1:491513753482:web:dd8b99c12ff35a00d0e273',
    messagingSenderId: '491513753482',
    projectId: 'hangnobita-52b73',
    authDomain: 'hangnobita-52b73.firebaseapp.com',
    databaseURL: 'https://hangnobita-52b73-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hangnobita-52b73.firebasestorage.app',
    measurementId: 'G-062Y68RRHH',
  );
}
